---
title: "Explore spectral variability"
author: "Victoria Scholl"
date: "08/13/2020 Earth Lab GRA"
output: html_document
---

```{r setup, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
library(stringr)
```


## Spectral variability for individuals with multiple observations across years.

```{r read_data}
all_spectra <- read.csv(here::here("data","cleaned_spectra.csv"))
```

```{r check_for_multiple_observations}
# see which individuals have multiple observations over time 
count_obs <- all_spectra %>%
  dplyr::group_by(individualID) %>% 
  filter(band_idx == "band1") %>%
  tally() 

table(count_obs$n)
```

Most individualIDs have just one spectrum, while others have two or three in the data set. 

```{r}
# find the individualIDs with more than 2 yearly observations
individuals_mult_obs <- all_spectra %>%
  distinct(individualID, spectraID) %>%
  count(individualID) %>%
  arrange(-n) %>% 
  filter(n>2)
  
individuals_mult_obs_subset <- individuals_mult_obs %>%
  head(n = 25)

individuals_mult_obs_subset %>% head(5)
```

```{r multiple_years_per_individual, include=FALSE}
current_indvdlID <- "NEON.PLA.D03.JERC.02220"
current_indvdlID <- "NEON.PLA.D03.OSBS.02053"
current_indvdlID <- "NEON.PLA.D08.DELA.04982"
current_indvdlID <- "NEON.PLA.D08.LENO.08763"
current_indvdlID <- "NEON.PLA.D13.NIWO.01346"

# list which dates have data for the current individual ID 
#all_spectra %>%
#  filter(individualID %in% current_indvdlID) %>%
#  group_by(spectraID) %>% 
#  tally()
```

```{r plot_multiple_obs_per_indvdlID, fig.height=12, fig.width=10}
# plot spectra with multiple observations across years. 
# facet by individual, color by year
all_spectra %>%
  filter(individualID %in% individuals_mult_obs_subset$individualID) %>% 
  ggplot(aes(wavelength_nm, ifelse(mask, NA, reflectance), 
             group = spectraID,
             color = as.factor(year))) + 
  facet_wrap(~individualID) + 
  geom_path() + 
  theme_minimal() + 
  scale_color_brewer(palette = "Accent") +
  labs(x = '\n Wavelength (nm)',
       y = 'Reflectance \n',
       color = "Year",
       title = paste0("Reflectance variation across years per individual"))
```

## Standard Deviation variation within species as a function of wavelength 

```{r sd_within_species, fig.height=12, fig.width=10}
# standard deviation for within species
sd_data_to_plot <- all_spectra %>% 
  # filter to keep only individualIDs with 3 
  filter(individualID %in% individuals_mult_obs$individualID) %>%
  # create a new column with genus and species
  unite(genusSpecies, c(genus, species), sep = " ") %>%
  group_by(wavelength_nm, genusSpecies, mask) %>%
  # calculate standard deviation within species
  summarize(sd = sd(reflectance)) 

sd_data_to_plot%>% 
  ggplot(aes(wavelength_nm, 
             ifelse(mask, NA, sd)),
         group = genusSpecies)+
  facet_wrap(~genusSpecies) + 
  geom_point(aes(color=sd), size =0.5) + 
  theme_minimal() + 
  scale_color_viridis_c() + 
  # scale_color_gradient2(#low = 'yellow',
  #                      mid = 'blue',
  #                      high = 'red',
  #                      # set midpoint as the median of SD values
  #                      midpoint = median(sd_data_to_plot$sd, na.rm=TRUE),
  #                      # set the color limits as the min and max SD values
  #                      limits = c(floor(min(sd_data_to_plot$sd, na.rm=TRUE)),
  #                                 ceiling(max(sd_data_to_plot$sd, na.rm=TRUE))),
  #                      # set point color for NA values
  #                      na.value = 'black',
  #                      space = 'Lab')+
  labs(x = '\n Wavelength (nm)',
       y = 'Standard Deviation \n',
       color = "SD",
       title = paste0("Standard deviation variation within species"))
```




## Spectra with 347nm starting wavelength

```{r include=FALSE, eval=FALSE}
spectraIDs_347nm <- all_spectra %>%
  dplyr::filter(band_idx == "band1") %>% 
  dplyr::filter(wavelength_nm == 347) %>% 
  dplyr::select(spectraID)

# split the spectraID strings to see which site is causing the 347nm starting wavelength
spectraIDs_347nm$neon_site <- stringr::str_split(as.character(spectraIDs_347nm$spectraID),
                   pattern = "[.]")[[1]][4]

print(unique(spectraIDs_347nm$neon_site))
```

They are all from the PUUM site, Pu'u Maka'ala Natural Area Reserve: https://www.neonscience.org/field-sites/field-sites-map/PUUM
