---
title: "Species at NEON NIWO"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(neonUtilities)
library(dplyr)
library(tidyverse)
library(kableExtra)
library(taxize) # scientific name to common name
```

## Download NEON data

```{r}
# Create output directory to store data
out_dir <- here::here("analysis","data","raw_data","NIWO")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

# Download the NEON Woody plant vegetation structure data for the NIWO site
neonUtilities::zipsByProduct(dpID = "DP1.10098.001",
                             site="NIWO",
                             savepath = out_dir,
                             check.size = FALSE)
neonUtilities::stackByTable(file.path(out_dir, "filesToStack10098"), folder = TRUE)
```

Read the mapping data and apparent individual data:

```{r read-map}
vegmap <- read_csv(file.path(out_dir, "filesToStack10098", "stackedFiles", 
                            "vst_mappingandtagging.csv")) %>%
  filter(!is.na(stemAzimuth), !is.na(pointID))
vegind <- read_csv(file.path(out_dir, "filesToStack10098", "stackedFiles",
                             "vst_apparentindividual.csv"))
```

Get precise locations for tagged plants and merge the mapping and individual data:

```{r get-precise-locs, warning=FALSE}
vegmap <- geoNEON::getLocTOS(vegmap, "vst_mappingandtagging")

samples_to_keep <- vegind %>%
  filter(plantStatus == "Live") %>%
  mutate(year = lubridate::year(date)) %>%
  group_by(individualID) %>%
  summarize(year = list(seq(min(year), max(year), by = 1))) %>%
  ungroup %>%
  unnest(year)

samples_to_keep %>%
  count(individualID) %>%
  arrange(-n)


veg <- as_tibble(vegmap) %>%
  group_by(individualID) %>%
  # some records are revised at later dates with better coordinates
  filter(!is.na(adjDecimalLatitude),
         date == max(date)) %>%
  ungroup %>%
  select(-date) %>%
  right_join(samples_to_keep) %>%
  distinct(individualID, year, .keep_all = TRUE)

veg %>%
  count(individualID, year) %>%
  arrange(-n)

veg %>%
  count(individualID) %>%
  arrange(-n)

nrow(vegmap)
nrow(veg)
```
```{r write-veg}
write_csv(veg, file.path(out_dir, "neon-veg_NIWO.csv"))
```


```{r make-veg-tibble}
species_counts <- veg %>%
  count(scientificName) %>%
    separate(scientificName, into = c('genus', 'species'), sep = ' ',
           extra = 'drop', remove = FALSE) %>%
  mutate(genusSpecies = paste(genus, species)) %>%
  arrange(-n) %>%
  na.omit() # remove rows with NA values

# number of mapped stems
message("total number of mapped stems")
sum(species_counts$n)


# histogram of taxons, Genus species
ggplot(species_counts, aes(y = reorder(genusSpecies, n), x = n)) + 
  geom_bar(stat = "identity") + 
  labs(title = "Histogram of species counts at NEON NIWO",
       y = "Genus species") + 
  theme_bw() 
```

```{r table_species_counts}
species_counts %>% 
  select(n, genusSpecies, genus, species, everything()) %>% 
  kableExtra::kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

Get common name from scientific name (this only works for some scientific names using taxize::sci2comm) so I'll add this column manually for now.

```{r}
# create empty column for common name data
species_counts$commonName <- NA

# automatically convert scientific name to common name?
for(i in 1:nrow(species_counts)){
  species_counts$commonName[i] <- taxize::sci2comm(species_counts$genusSpecies[i])
}

# add common names automatically since they don't all populate
species_counts$commonName <- c("Engelmann spruce", 
                               "subalpine fir", 
                               "lodgepole pine",
                               "limber pine",
                               "willows",
                               "shrubby cinquefoil",
                               "common juniper")

# table 
species_counts %>% 
  select(n, genusSpecies, genus, species, everything()) %>% 
  kableExtra::kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

